### ISSUE TITLE
Crypto replace required on some(?) systems

### ISSUE THREAD

**Issue by 0x0000beef** [ilyakharlamov/bookmate_downloader#12]
As a user of Linux Mint and python 3.10.6...
```
Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Xfce 4.16.0
    tk: Gtk 3.24.23 wm: xfwm dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
```
...I came across a problem in using the script:
```
Traceback (most recent call last):
  File "/home/.../bookmate_downloader/src/python3/bookmate_downloader.py", line 249, in <module>
    book.download()
  File "/home/.../bookmate_downloader/src/python3/bookmate_downloader.py", line 133, in download
    metadata = self.decrypt_metadata(encrypted_metadata, self.secret)
  File "/home/.../bookmate_downloader/src/python3/bookmate_downloader.py", line 148, in decrypt_metadata
    metadata[key] = self.decrypt(secret, bytess(val))
  File "/home/.../bookmate_downloader/src/python3/bookmate_downloader.py", line 156, in decrypt
    bts = self.rawDecryptBytes(data[16:], key, data[:16])
  File "/home/.../bookmate_downloader/src/python3/bookmate_downloader.py", line 166, in rawDecryptBytes
    cipher = AES.new(key, AES.MODE_CBC, iv)
  File "/home/.../.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/.../.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/.../.local/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```
This SO answer helped me: https://stackoverflow.com/a/73713926
```
pip uninstall pycrypto
pip install pycryptodome
```
requirements короче надо обновить наверное. Или дополнить описание.

**Comment by Vonsaum** [comment]
How did you manage to find the BMS cookie? I don't have one. Maybe it's because bookmate became part of Yandex services.

**Comment by 0x0000beef** [comment]
If I understand correctly, the BMS cookie is given differently for different browsers - the right one can be pulled from chrome-like browsers, not from firefox (Brave in my case). Yes, Bookmate is now part of Ya, but for non-russian ip everything works as before (at least it did a couple of weeks ago)

**Comment by alex123012** [comment]
If you're from Russia - you can check this fork: https://github.com/alex123012/yandex_books_downloader
